
export const NotificationType = {
    MAINTENANCE: 'MAINTENANCE',
    PAYMENT: 'PAYMENT',
    EXPENSE: 'EXPENSE',
    MESSAGE: 'MESSAGE',
    LEASE_AGREEMENT: 'LEASE_AGREEMENT',
    SUBSCRIPTION: 'SUBSCRIPTION',
} as const;